const state={payload:null,products:[],cart:new Map(),search:"",typeFilter:"all",availableOnly:false,sort:"page_order",eurJpy:170,fedex:30,dutyRate:.027,vatRate:.19};
const scenarios=[1,2,5,10,12,24,48];
const shippingTable=[[1,4500],[2,4500],[2.5,5500],[3,6100],[3.5,6700],[4,7300],[4.5,7900],[5,8400],[5.5,9900],[6,10400],[6.5,10800],[7,11300],[7.5,11800],[8,12200],[8.5,12700],[9,13200],[9.5,14900],[10,15400],[10.5,15700],[11,16100],[11.5,16500],[12,16900],[12.5,18500],[13,18900],[13.5,19300],[14,19800],[14.5,20200],[15,20600],[15.5,21000],[16,22900],[16.5,23300],[17,23800],[17.5,24200],[18,24600],[18.5,25100],[19,25500],[19.5,25900],[20,26300],[20.5,26800],[21,27700],[21.5,29000],[22,29000],[22.5,30100],[23,30100],[23.5,31600],[24,31600],[24.5,32900],[25,32900],[25.5,38900],[26,38900],[26.5,40200],[27,40200],[27.5,41500],[28,41500],[28.5,42800],[29,42800],[29.5,44100],[30,44100],[30.5,45400],[31,45400],[31.5,46800],[32,46800],[32.5,48100],[33,48100],[33.5,49400],[34,49400],[34.5,50700],[35,50700],[35.5,52000],[36,52000],[36.5,53300],[37,53300],[37.5,54700],[38,54700],[38.5,56000],[39,56000],[39.5,56800],[40,56800],[40.5,57000],[41,57000],[41.5,57200],[42,57200],[42.5,57400],[43,57400],[43.5,57700],[44,57700],[44.5,61500],[45,61500],[45.5,62800],[46,62800],[46.5,64100],[47,64100],[47.5,65300],[48,65300],[48.5,66600],[49,66600],[49.5,67800],[50,67800],[50.5,69100],[51,69100],[51.5,70400],[52,70400],[52.5,71500],[53,71500],[53.5,72900],[54,72900],[54.5,74200],[55,74200],[55.5,75400],[56,75400],[56.5,76700],[57,76700],[57.5,77900],[58,77900],[58.5,79200],[59,79200],[59.5,80500],[60,80500],[60.5,81700],[61,81700],[61.5,83000],[62,83000],[62.5,84300],[63,84300],[63.5,85500],[64,85500],[64.5,86800],[65,86800],[65.5,88100],[66,88100],[66.5,89300],[67,89300],[67.5,90600],[68,90600],[68.5,92600],[69,92600],[69.5,93900],[70,93900],[70.5,95300],[71,95300],[71.5,96600],[72,96600],[72.5,98000],[73,98000],[73.5,99300],[74,99300],[74.5,100600],[75,100600],[75.5,102000],[76,102000],[76.5,103300],[77,103300],[77.5,104700],[78,104700],[78.5,106000],[79,106000],[79.5,107400],[80,107400],[80.5,108700],[81,108700],[81.5,110000],[82,110000],[82.5,111400],[83,111400],[83.5,112700],[84,112700],[84.5,114100],[85,114100],[85.5,115400],[86,115400],[86.5,116700],[87,116700],[87.5,118100],[88,118100]];
const $=id=>document.getElementById(id);
function b64ToBytes(b64){return Uint8Array.from(atob(b64),c=>c.charCodeAt(0))}
async function deriveKey(password,salt,iterations){const enc=new TextEncoder();const baseKey=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations,hash:"SHA-256"},baseKey,{name:"AES-GCM",length:256},false,["decrypt"])}
async function decryptData(password){const res=await fetch(`data/products.enc.json?t=${Date.now()}`,{cache:"no-store"});const encrypted=await res.json();const salt=b64ToBytes(encrypted.salt);const nonce=b64ToBytes(encrypted.nonce);const ciphertext=b64ToBytes(encrypted.ciphertext);const key=await deriveKey(password,salt,encrypted.iterations||250000);const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:nonce},key,ciphertext);return JSON.parse(new TextDecoder().decode(plain))}
async function fetchFxRate(){const info=$("fxInfo");try{const res=await fetch("https://api.frankfurter.dev/v2/rates?base=EUR&quotes=JPY",{cache:"no-store"});if(!res.ok)throw new Error("FX HTTP "+res.status);const data=await res.json();const rate=data?.rates?.JPY;if(!rate)throw new Error("JPY missing");state.eurJpy=Number(rate);$("eurJpy").value=Number(rate).toFixed(4);info.textContent=`Automatisch geladen: ${Number(rate).toFixed(4)} JPY je EUR · ${data.date||""}`;renderProducts()}catch(e){info.textContent="Automatischer Kurs nicht erreichbar. Manuell prüfen."}}
function money(v){if(v==null||Number.isNaN(v))return"-";return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v)}
function yen(v){if(v==null||Number.isNaN(v))return"-";return`¥${new Intl.NumberFormat("de-DE").format(Math.round(v))}`}
function productKey(i){return`${i.product_name}||${i.url||""}`}
function variantKey(i){return`${i.product_name}||${i.variant}||${i.variant_value||""}||${i.url||""}`}
function isAvailable(i){return Number(i.stock||0)>0&&!String(i.variant||"").toLowerCase().includes("sold out")}
function deriveItemType(n,v){const t=`${n||""} ${v||""}`.toLowerCase();if(t.includes("case"))return"case";if(t.includes("pack"))return"pack";if(t.includes("no shrink")||t.includes("noshrink"))return"no_shrink";if(t.includes("damaged"))return"damaged";return"box"}
function normalizeProducts(products){return(products||[]).map((i,idx)=>({...i,product_order:Number(i.product_order||999999),variant_order:Number(i.variant_order||idx),yen_price:Number(i.yen_price||0),stock:Number(i.stock||0),weight_grams:Number(i.weight_grams||320),item_type:i.item_type||deriveItemType(i.product_name,i.variant)}))}
function filteredProducts(){let rows=[...state.products];if(state.search.trim()){const q=state.search.trim().toLowerCase();rows=rows.filter(x=>`${x.product_name} ${x.product_code||""} ${x.variant||""}`.toLowerCase().includes(q))}if(state.typeFilter!=="all")rows=rows.filter(x=>x.item_type===state.typeFilter);if(state.availableOnly)rows=rows.filter(isAvailable);if(state.sort==="page_order")rows.sort((a,b)=>(a.product_order-b.product_order)||(a.variant_order-b.variant_order));if(state.sort==="price_asc")rows.sort((a,b)=>(a.yen_price||0)-(b.yen_price||0));if(state.sort==="price_desc")rows.sort((a,b)=>(b.yen_price||0)-(a.yen_price||0));if(state.sort==="stock_desc")rows.sort((a,b)=>(b.stock||0)-(a.stock||0));if(state.sort==="name_asc")rows.sort((a,b)=>String(a.product_name).localeCompare(String(b.product_name)));return rows}
function groupRows(rows){const map=new Map();for(const item of rows){const key=productKey(item);if(!map.has(key))map.set(key,{product_order:item.product_order,product_name:item.product_name,product_code:item.product_code,url:item.url,variants:[]});map.get(key).variants.push(item)}const groups=[...map.values()];groups.sort((a,b)=>a.product_order-b.product_order);for(const g of groups)g.variants.sort((a,b)=>a.variant_order-b.variant_order);return groups}
function renderStats(rows){$("statLoadedProducts").textContent=new Set(state.products.map(productKey)).size;$("statLoadedVariants").textContent=state.products.length;$("statVisibleProducts").textContent=new Set(rows.map(productKey)).size;$("statVisibleVariants").textContent=rows.length;const m=state.payload?.meta||{};$("metaLine").textContent=`Letzter Export: ${m.generated_at||"-"} · Quelle: ${m.source_file||"-"} · Händler-Reihenfolge aktiv`}
function getShippingYen(kg){for(const [max,price] of shippingTable){if(kg<=max)return price}return null}
function singleScenarioCost(item,qty){const rate=Number(state.eurJpy||170),fedex=Number(state.fedex||30),dutyRate=Number(state.dutyRate||.027),vatRate=Number(state.vatRate||.19);const goodsYen=(item.yen_price||0)*qty,goodsEur=goodsYen/rate,weightKg=((item.weight_grams||320)*qty)/1000,shippingYen=getShippingYen(weightKg);if(!shippingYen)return null;const shippingEur=shippingYen/rate,dutyBase=goodsEur+shippingEur,duty=dutyBase*dutyRate,vat=dutyBase*vatRate,total=goodsEur+shippingEur+fedex+duty+vat;return total/qty}
function renderPreview(item){return scenarios.map(q=>{const c=singleScenarioCost(item,q);return`<div class="preview-pill"><span>${q}x</span><strong>${c?money(c):"-"}</strong></div>`}).join("")}
function renderProducts(){const rows=filteredProducts();renderStats(rows);const groups=groupRows(rows),container=$("productList");container.innerHTML="";for(const g of groups){const card=document.createElement("section");card.className="product-group";card.innerHTML=`<div class="product-header"><div><div class="product-order">#${g.product_order}</div><h3>${escapeHtml(g.product_name)}</h3><p>${escapeHtml(g.product_code||"")}</p></div><a href="${g.url||"#"}" target="_blank" rel="noopener">Otakuya öffnen</a></div><div class="variant-table"><div class="variant-row variant-head"><div>Menge</div><div>Variante</div><div>Preis</div><div>Bestand</div><div>Gewicht</div><div>Schnellvorschau All-in pro Stück</div></div>${g.variants.map(variantRow).join("")}</div>`;container.appendChild(card)}document.querySelectorAll(".qty-input").forEach(input=>input.addEventListener("input",e=>{const key=e.target.dataset.key,qty=Math.max(0,Number(e.target.value||0));if(qty>0)state.cart.set(key,qty);else state.cart.delete(key);renderCart()}));renderCart()}
function variantRow(item){const key=variantKey(item),qty=state.cart.get(key)||0,soldOut=!isAvailable(item);return`<div class="variant-row ${soldOut?"sold-out":""}"><div><input class="qty-input" inputmode="numeric" type="number" min="0" value="${qty}" data-key="${escapeAttr(key)}"/></div><div class="variant-title"><strong>${escapeHtml(item.variant||"-")}</strong><span class="badge ${escapeAttr(item.item_type)}">${escapeHtml(typeLabel(item.item_type))}</span>${soldOut?`<span class="badge sold">sold out</span>`:""}</div><div class="price">${yen(item.yen_price)}</div><div class="stock ${soldOut?"empty":"ok"}">${item.stock??"-"} pcs</div><div>${item.weight_grams??"-"} g</div><div class="preview">${renderPreview(item)}</div></div>`}
function typeLabel(t){return({box:"Box",case:"Case",pack:"Pack",no_shrink:"No Shrink",damaged:"Damaged"})[t]||t||"Box"}
function calculateCart(){const selected=[],byKey=new Map(state.products.map(x=>[variantKey(x),x]));for(const [key,qty]of state.cart.entries()){const item=byKey.get(key);if(item&&qty>0)selected.push({...item,qty})}if(!selected.length)return null;const rate=Number(state.eurJpy||170),fedex=Number(state.fedex||30),dutyRate=Number(state.dutyRate||.027),vatRate=Number(state.vatRate||.19);const totalQty=selected.reduce((s,x)=>s+x.qty,0),totalYen=selected.reduce((s,x)=>s+x.qty*(x.yen_price||0),0),totalWeightKg=selected.reduce((s,x)=>s+(x.qty*(x.weight_grams||320))/1000,0),shippingYen=getShippingYen(totalWeightKg);if(!shippingYen)return{selected,error:"Kein Versandwert für dieses Gewicht gefunden."};const shippingEur=shippingYen/rate;const lines=selected.map(item=>{const lineYen=item.qty*(item.yen_price||0),lineWeightKg=(item.qty*(item.weight_grams||320))/1000,weightShare=lineWeightKg/totalWeightKg,qtyShare=item.qty/totalQty,lineGoodsEur=lineYen/rate,lineShippingEur=shippingEur*weightShare,lineFedexEur=fedex*qtyShare,dutyBase=lineGoodsEur+lineShippingEur,duty=dutyBase*dutyRate,vat=dutyBase*vatRate,allInLine=lineGoodsEur+lineShippingEur+lineFedexEur+duty+vat,allInUnit=allInLine/item.qty;return{...item,lineYen,lineWeightKg,lineGoodsEur,lineShippingEur,lineFedexEur,duty,vat,allInLine,allInUnit}});return{selected,lines,totalQty,totalYen,totalWeightKg,shippingYen,shippingEur,allInTotal:lines.reduce((s,x)=>s+x.allInLine,0)}}
function renderCart(){state.eurJpy=Number($("eurJpy").value||170);state.fedex=Number($("fedex").value||30);state.dutyRate=Number($("dutyRate").value||.027);state.vatRate=Number($("vatRate").value||.19);const r=calculateCart(),box=$("cartBox");if(!r){box.innerHTML=`<p class="muted">Noch keine Mengen ausgewählt.</p>`;return}if(r.error){box.innerHTML=`<p class="error">${escapeHtml(r.error)}</p>`;return}box.innerHTML=`<div class="cart-summary-grid"><div><span>Menge</span><strong>${r.totalQty}</strong></div><div><span>Gewicht</span><strong>${r.totalWeightKg.toFixed(3)} kg</strong></div><div><span>Warenwert</span><strong>${yen(r.totalYen)}</strong></div><div><span>Versand</span><strong>${yen(r.shippingYen)}</strong></div><div><span>All-in gesamt</span><strong>${money(r.allInTotal)}</strong></div></div><div class="cart-lines">${r.lines.map(line=>`<div class="cart-line"><div><strong>${escapeHtml(line.product_name)}</strong><span>${escapeHtml(line.variant)} · ${line.qty}x · ${yen(line.yen_price)}</span></div><div><strong>${money(line.allInUnit)}</strong><span>pro Stück all-in</span></div></div>`).join("")}</div>`}
function exportCartCsv(){const r=calculateCart();if(!r||r.error)return;const header=["qty","product_name","variant","yen_price","stock","weight_grams","all_in_unit_eur","line_total_eur","url"];const lines=r.lines.map(x=>[x.qty,x.product_name,x.variant,x.yen_price,x.stock,x.weight_grams,x.allInUnit.toFixed(2),x.allInLine.toFixed(2),x.url||""]);const csv=[header,...lines].map(row=>row.map(cell=>`"${String(cell??"").replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="otakuya_cart.csv";a.click();URL.revokeObjectURL(url)}
async function copySummary(){const r=calculateCart();if(!r||r.error)return;const text=[`Otakuya Warenkorb`,`Menge: ${r.totalQty}`,`Gewicht: ${r.totalWeightKg.toFixed(3)} kg`,`Warenwert: ${yen(r.totalYen)}`,`Versand: ${yen(r.shippingYen)}`,`All-in gesamt: ${money(r.allInTotal)}`].join("\n");await navigator.clipboard.writeText(text)}
function escapeHtml(t){return String(t??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function escapeAttr(t){return escapeHtml(t).replace(/"/g,"&quot;")}
function bindControls(){$("unlockBtn").addEventListener("click",async()=>{const pw=$("password").value;$("unlockError").textContent="";try{const payload=await decryptData(pw);state.payload=payload;state.products=normalizeProducts(payload.products);$("lockScreen").classList.add("hidden");$("dashboard").classList.remove("hidden");await fetchFxRate();renderProducts()}catch(e){$("unlockError").textContent="Passwort falsch oder Daten konnten nicht entschlüsselt werden.";console.error(e)}});$("password").addEventListener("keydown",e=>{if(e.key==="Enter")$("unlockBtn").click()});$("search").addEventListener("input",e=>{state.search=e.target.value;renderProducts()});$("typeFilter").addEventListener("change",e=>{state.typeFilter=e.target.value;renderProducts()});$("availableOnly").addEventListener("change",e=>{state.availableOnly=e.target.checked;renderProducts()});$("sort").addEventListener("change",e=>{state.sort=e.target.value;renderProducts()});["eurJpy","fedex","dutyRate","vatRate"].forEach(id=>$(id).addEventListener("input",()=>{renderProducts();renderCart()}));$("refreshBtn").addEventListener("click",()=>location.reload());$("clearCartBtn").addEventListener("click",()=>{state.cart.clear();renderProducts()});$("exportCsvBtn").addEventListener("click",exportCartCsv);$("copySummaryBtn").addEventListener("click",copySummary)}
document.addEventListener("DOMContentLoaded",bindControls);
